#!/bin/sh

set -eux

dir="${BUILDDIR:-build}"
install_dir="${INSTALLDIR:-$(pwd)/install}"
: ${JOBS:=$(($(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2) * 2))}
cmake -S . -B "${dir}"
cmake --build "${dir}" --parallel "${JOBS}" --target doc
mkdir -p "${install_dir}/usr/local/share/doc/ccache" \
         "${install_dir}/usr/local/share/man/man1"
for name in LICENSE AUTHORS MANUAL NEWS; do
  [ -f "${dir}/${name}.html" ] && cp "${dir}/${name}.html" "${install_dir}/usr/local/share/doc/ccache/"
  [ -f "${dir}/${name}.md" ] && cp "${dir}/${name}.md" "${install_dir}/usr/local/share/doc/ccache/"
done
cp "${dir}/ccache.1" "${install_dir}/usr/local/share/man/man1/"
